# Generated by Django 2.2.4 on 2019-08-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0003_student_no_dues'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, help_text='Required', max_length=150, null=True),
        ),
    ]
