# Generated by Django 2.2.4 on 2019-08-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0004_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(default='info@example.com', help_text='Required', max_length=150, unique=True),
        ),
    ]
