# Generated by Django 2.2.4 on 2019-08-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0005_auto_20190829_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
