# Generated by Django 2.2.4 on 2019-08-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0006_student_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
