# Generated by Django 2.2.4 on 2019-08-31 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0007_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
