# Generated by Django 2.2.4 on 2019-08-31 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selection', '0008_auto_20190831_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='token',
        ),
    ]
