# Generated by Django 2.2.4 on 2020-01-07 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0005_college_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_year', models.DateField(blank=True, null=True)),
                ('course_type', models.CharField(blank=True, choices=[('FT', 'FullTime'), ('PT', 'PartTime'), ('CT', 'Correspondence')], default='FT', help_text='Select Course type.', max_length=10)),
                ('college_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.College')),
            ],
        ),
    ]
