# Generated by Django 2.2.4 on 2020-01-07 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Enter the course name', max_length=50),
            preserve_default=False,
        ),
    ]
