# Generated by Django 2.2.4 on 2020-01-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20200108_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(blank=True, choices=[('FT', 'FullTime'), ('PT', 'PartTime'), ('CT', 'Correspondence')], default='FullTime', help_text='Select Course type.', max_length=10),
        ),
    ]
