# Generated by Django 2.2.4 on 2020-01-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20200110_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_sn',
            field=models.CharField(blank=True, default=None, help_text='course short name', max_length=50, null=True),
        ),
    ]
