# Generated by Django 2.2.4 on 2020-01-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='detail',
            field=models.TextField(blank=True, default='some course detail', null=True),
        ),
    ]
