# Generated by Django 2.2.4 on 2019-12-22 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(help_text='Enter the state name', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='state_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='urban_name',
        ),
        migrations.CreateModel(
            name='Urban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urban_name', models.CharField(help_text='Enter the state name', max_length=100)),
                ('state_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.State')),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='country_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Country'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(help_text='Enter the state name', max_length=100)),
                ('state_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.State')),
            ],
        ),
    ]
