# Generated by Django 2.2.4 on 2019-12-23 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_auto_20191222_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(help_text='Enter the state name', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(help_text='Enter the country name: ', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='urban',
            name='urban_name',
            field=models.CharField(help_text='Enter the state name', max_length=100, unique=True),
        ),
    ]
