# Generated by Django 2.2.4 on 2019-12-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20191223_0453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urban',
            name='urban_name',
            field=models.CharField(help_text='Enter the state name', max_length=100),
        ),
    ]
