# Generated by Django 2.2.4 on 2020-01-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_auto_20191223_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(default='abcd'),
        ),
    ]
