# Generated by Django 2.2.4 on 2020-01-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_state_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='slug',
            new_name='state_slug',
        ),
    ]
