# Generated by Django 2.2.4 on 2020-01-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0007_auto_20200109_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='state',
            old_name='state_slug',
            new_name='slug',
        ),
    ]
