# Generated by Django 2.2.4 on 2020-01-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0008_auto_20200109_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(),
        ),
    ]
