# Generated by Django 2.2.4 on 2020-01-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0009_auto_20200109_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='some-slug'),
        ),
    ]
