# Generated by Django 2.2.4 on 2020-01-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0010_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
