# Generated by Django 2.2.4 on 2019-08-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
