# Generated by Django 2.2.4 on 2019-08-24 11:03

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190818_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=products.models.upload_location, width_field='width_field'),
        ),
    ]
