# Generated by Django 2.2.4 on 2019-12-21 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_auto_20191221_0958'),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='country',
            new_name='country_id',
        ),
        migrations.AddField(
            model_name='university',
            name='college_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.College'),
        ),
    ]
