# Generated by Django 2.2.4 on 2019-12-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20191221_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='college_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='colleges.College'),
        ),
        migrations.AlterField(
            model_name='university',
            name='country_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Country'),
        ),
    ]
