# Generated by Django 2.2.4 on 2019-12-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_university_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_type', models.CharField(help_text='Enter the university type eg: private, state, deemed, central.', max_length=100)),
                ('university', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.University')),
            ],
        ),
    ]
