# Generated by Django 2.2.4 on 2019-12-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_universitytype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitytype',
            old_name='university_type',
            new_name='type',
        ),
    ]
