# Generated by Django 2.2.4 on 2019-12-26 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_auto_20191226_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitytype',
            name='university',
        ),
        migrations.AddField(
            model_name='university',
            name='university_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.UniversityType'),
        ),
    ]
