# Generated by Django 2.2.4 on 2019-12-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_university_state_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
