# Generated by Django 2.2.4 on 2020-01-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter course category eg arts, science etc', max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
