# Generated by Django 2.2.4 on 2020-04-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(blank=True, default=1, verbose_name=50),
        ),
    ]
