# Generated by Django 2.2.4 on 2020-04-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='duration',
            field=models.IntegerField(blank=True, default=1, max_length=50),
        ),
    ]
