# Generated by Django 2.2.4 on 2019-12-21 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='college',
            old_name='name',
            new_name='college_name',
        ),
        migrations.RenameField(
            model_name='college',
            old_name='university',
            new_name='university_id',
        ),
    ]
