# Generated by Django 2.2.4 on 2019-12-21 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_auto_20191221_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='university_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.University'),
        ),
    ]
