# Generated by Django 2.2.4 on 2020-01-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_college_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
