# Generated by Django 2.2.4 on 2020-01-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_college_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='slug',
            field=models.SlugField(default='college'),
        ),
    ]
