# Generated by Django 2.2.4 on 2020-01-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0007_auto_20200110_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='slug',
            field=models.SlugField(default='college', max_length=100),
        ),
    ]
