# Generated by Django 2.2.4 on 2020-01-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_auto_20200110_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='graduate',
            field=models.CharField(blank=True, choices=[('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('Ph.D', 'Doctrate'), ('Diploma', 'Diploma'), ('Technical', 'Technical')], default='Under Graduate', max_length=20),
        ),
    ]
