# Generated by Django 2.2.4 on 2020-01-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_detail'),
        ('colleges', '0009_college_graduate'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='course_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='name', to='courses.Course'),
        ),
    ]
