# Generated by Django 2.2.4 on 2020-01-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0010_college_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='graduate',
            field=models.CharField(blank=True, choices=[('UG', 'Under Graduate'), ('PG', 'Post Graduate'), ('Ph.D', 'Doctrate'), ('Diploma', 'Diploma'), ('Technical', 'Technical')], default='UG', max_length=20),
        ),
    ]
